// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApAtefHXPYvWYeikvFf7smJIVAbBjcSc0',
    appId: '1:897934415319:web:3e2ac3ea94195fd4122792',
    messagingSenderId: '897934415319',
    projectId: 'fominhas-7ee47',
    authDomain: 'fominhas-7ee47.firebaseapp.com',
    storageBucket: 'fominhas-7ee47.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkn-heippU_UP2vlatqGz4iZdjBBjs4Do',
    appId: '1:897934415319:android:d9df5a281b7f2730122792',
    messagingSenderId: '897934415319',
    projectId: 'fominhas-7ee47',
    storageBucket: 'fominhas-7ee47.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfHQ6jLaf0Dz7ExeTpJtL-FmRVXOuXR_g',
    appId: '1:897934415319:ios:d266d6b21af3fda4122792',
    messagingSenderId: '897934415319',
    projectId: 'fominhas-7ee47',
    storageBucket: 'fominhas-7ee47.firebasestorage.app',
    iosBundleId: 'com.fominhas.app',
  );
}
